# Generated by Django 5.2.16 on 2026-07-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("label_created", "Label Created"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("exception", "Exception"),
                            ("returned", "Returned"),
                        ],
                        max_length=32,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("event_timestamp", models.DateTimeField()),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["shipment", "-event_timestamp"],
                        name="tracking_tr_shipmen_bef772_idx",
                    )
                ],
            },
        ),
    ]
