# Generated by Django 5.2.16 on 2026-07-27 11:33

import shipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=14,
                        unique=True,
                        validators=[shipments.models.validate_tracking_number],
                    ),
                ),
                ("sender_name", models.CharField(max_length=255)),
                ("recipient_name", models.CharField(max_length=255)),
                ("sender_address", models.TextField()),
                ("recipient_address", models.TextField()),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("current_location", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("label_created", "Label Created"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("exception", "Exception"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="label_created",
                        max_length=32,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("express", "Express"),
                            ("overnight", "Overnight"),
                            ("international", "International"),
                            ("freight", "Freight"),
                        ],
                        default="standard",
                        max_length=32,
                    ),
                ),
                ("carrier", models.CharField(default="CourierTrack", max_length=100)),
                (
                    "package_weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in lbs", max_digits=8
                    ),
                ),
                (
                    "package_dimensions",
                    models.CharField(help_text="L x W x H in inches", max_length=100),
                ),
                ("estimated_delivery_date", models.DateField()),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                (
                    "origin_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "origin_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "current_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "current_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "destination_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "destination_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tracking_number"],
                        name="shipments_s_trackin_80db53_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="shipments_s_status_c4d56f_idx",
                    ),
                ],
            },
        ),
    ]
