# Generated by Django 5.2.16 on 2026-07-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="package_contents",
            field=models.TextField(
                blank=True, help_text="Shipment contents or items in the package"
            ),
        ),
    ]
